name: Deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Deploy
        run: |
          npm install
          npm run build
