name: Deploy

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Build image
        run: docker build -t ${{ github.repository }} .
      - name: Deploy image
        run: |
          docker stop ${{ github.repository }} || true
          docker rm ${{ github.repository }} || true
          docker run -p 3000:3000 -d ${{ github.repository }}
